// Generated by Wrangler on Thu Apr 04 2024 10:02:20 GMT-0400 (Atlantic Standard Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	DB: D1Database;
}
